name: "ec2-instance-connect-deploy"
description: "Deploy to AWS EC2 instance using EC2 Instance Connect"
branding:
  icon: fast-forward
  color: orange

inputs:
  access-key-id:
    description: "AWS_ACCESS_KEY_ID"
    required: true
  secret-access-key:
    description: "AWS_SECRET_ACCESS_KEY"
    required: true
  default-region:
    description: "AWS_DEFAULT_REGION"
    required: true
  local-path:
    description: "The local path"
    required: true
  remote-path:
    description: "The remote path"
    required: true
  instance-id:
    description: "The EC2 instance id"
    required: true
  user-name:
    description: "The user name"
    required: true
  rsync-args:
    description: 'rsync args'
    required: true
    default: "--stats --progress"        
  mssh-path:
    description: 'Path to mssh'
    required: true
    default: "/home/ubuntu/.local/bin/mssh"        
outputs:
  result:
    description: "Output of the command"
    value: ${{ steps.ec2-deploy.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: ec2-deploy
      shell: bash
      run: |
        AWS_ACCESS_KEY_ID=${{ inputs.access-key-id }} \
        AWS_SECRET_ACCESS_KEY=${{ inputs.secret-access-key }} \
        AWS_DEFAULT_REGION=${{ inputs.default-region }}
        
        rsync -a ${{ inputs.rsync-args }} -e "${{ inputs.mssh-path }} -r ${AWS_DEFAULT_REGION}" ${{ inputs.local-path }} "${{ inputs.user-name }}@${{ inputs.instance-id }}:${{ inputs.remote-path }}" > action_output
        
        tr  '\n' '--'  < action_output > single_lined_output
     
        content=`cat single_lined_output`
        echo "result=$(cat single_lined_output)" >> $GITHUB_OUTPUT

        rm action_output
        rm single_lined_output